---
- name: Ensure firewalld is running and enabled (RedHat)
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: true
  when: ansible_facts.os_family == "RedHat"

- name: Ensure ufw is running and enabled (Debian)
  ansible.builtin.systemd:
    name: ufw
    state: started
    enabled: true
  when: ansible_facts.os_family == "Debian"

- name: Open ports in firewalld (RedHat)
  ansible.builtin.command:
    cmd: "firewall-cmd --permanent --add-port={{ item }}/tcp"
  loop: "{{ firewall_ports }}"
  register: firewall_output
  changed_when: "'ALREADY ENABLED' not in (firewall_output.stderr | default(''))"
  when: ansible_facts.os_family == "RedHat"
  notify: Reload firewalld

- name: Open ports in firewall (Debian)
  ansible.builtin.command:
    cmd: "ufw allow {{ item }}/tcp"
  loop: "{{ firewall_ports }}"
  when: ansible_facts.os_family == "Debian"
  changed_when: false
  notify: Reload ufw
